### PR TITLE
Added Nearest neighbor search for nodes.

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
nearest neighbor search for nodes is based on scipy.spatial.cKDtree.

The key issue here is that pyugrid is now dependent on scipy.

It is optional -- it will only get imported if it is used, but the tests, at least, do use it.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ChrisBarker-NOAA , can you fix these tests?

**Comment by ChrisBarker-NOAA** [comment]
I"ll look more, but it looks like it's not finding scipy -- but it's in the requirements. And it looks like Travis is installing it.

Also, matplotlib for a notebook. That's not in the requirements....

**Comment by daf** [comment]
@ChrisBarker-NOAA Travis is installing scipy 0.9.0, hard to be certain but it looks like `scipy.spatial.cKDTree` [came in 0.12.0](http://docs.scipy.org/doc/scipy/reference/release.0.12.0.html)?  Can travis be reworked to use pip or miniconda?  I've had more success with them.

**Comment by daf** [comment]
As for the notebooks, maybe the test runner should be changed to `py.test test/` or something to skip collection of the notebooks.  I don't know why it does that by default.

**Comment by ChrisBarker-NOAA** [comment]
@ChrisBarker-NOAA <https://github.com/ChrisBarker-NOAA> Travis is
installing scipy 0.9.0,


Ouch! That's an old one -- we really need to do something about that.

-CHB


hard to be certain but it looks like scipy.spatial.cKDTree came in 0.12.0
<http://docs.scipy.org/doc/scipy/reference/release.0.12.0.html>? Can travis
be reworked to use pip or miniconda? I've had more success with them.

—
Reply to this email directly or view it on GitHub
<https://github.com/pyugrid/pyugrid/pull/37#issuecomment-119588212>.

**Comment by daf** [comment]
:+1:

**Pull request merged**
