### PR TITLE
Updated, cleaned, and added new notebook examples.

### LINKED ISSUE #108: Check / update notebook examples with Cartopy.
We should make sure these still work.

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #108,#106, #60, and #23.

See the notebooks [here](http://nbviewer.jupyter.org/github/ocefpaf/pyugrid/blob/notebooks_example/notebook_examples/index.ipynb).

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rsignell-usgs I believe that this PR is more up to your alley, no? Can you review it?

**Comment by ocefpaf** [comment]
@rsignell-usgs the goals of this PR are:

- plotting examples;
- demonstrate how we leverage the UGRID conventions to read different models;
- explain what is the connective array and how to use it.

You'll notice problems with iris and cartopy/matplotlib along the way, but I think that these problems should be in the notebook as we work them out.

**Comment by rsignell-usgs** [comment]
Okay, I was skeptical to accept a PR with errors, especially Iris errors, but since this isn't a release version, I guess this is fine.

**Comment by rsignell-usgs** [comment]
@ocefpaf nice job with the simple notebook examples, BTW.     And now that I think of it, accepting this PR with the Iris error might help us get that Iris issue or dataset issue sorted out more quickly

**Comment by ocefpaf** [comment]
> Okay, I was skeptical to accept a PR with errors, especially Iris errors, but since this isn't a release version, I guess this is fine.

We have a few options there, besides the obvious way to proceed that is to report that error, those are:

- use something different from iris to show interoperability;
- give up in interoperability and use raw netCDF4;
- write a better reason for using iris there and how that error will be addressed.

As it is a real life example I believe that showing the error is only fair with the users.

**Pull request merged**
