### PR TITLE
2D Flexible mesh

### PR DESCRIPTION
**Pull request by SiggyF**
I was working on using pyugrid for Delft3D Flexible Mesh. Following up on the discussion in #96 I started on improving the support for flexible mesh. I foresaw the following tasks, some of which I added to this pull request, which I consider work in progress. 

- [x] Add an example file based on the [flexible mesh section](http://ugrid-conventions.github.io/ugrid-conventions/#2d-flexible-mesh-mixed-triangles-quadrilaterals-etc-topology) in the convention
- [x] Provide a real world example (in the notebooks). Example added, based on Delft3D Flexible Mesh. 
- [x] Add  testcases that test if faces, edges, etc.. are returned as masked arrays, with masks for unfilled nodes (e.g last node in the triangle in example above). (1 test case added so far)
- [x] Update documentation

For the next pull request
- [ ] de-triangulate

I ran into a few questions which you could perhaps help out with:
- should I create a PR based on master or develop?
- I noticed that a lot of tests are currently failing (both local and in travis, both for develop and for master), am I doing something wrong or is this a correct reflection of the current state? If so please consider to skip broken tests until fixed.
- Some .nc files are created in test/files. What is the expected organization of test files and scripts that create them?
- @bekozi, please have a look and see how this fits in with the pull request you were working on in #96 

Thanks for your help. 

Fedor @ Deltares

### CODE REVIEW

**Comment by jay-hennen** [comment]
1. Best to create the PR on develop. Master is very old at this point, and the latest releases point to develop. Develop also has the latest point-in-cell location (now compatible with mixed meshes!)
2. Tests should work much better in develop.

Cool to see work on flexible meshes! The mesh still doesn't change with time though, right?

**Comment by ChrisBarker-NOAA** [comment]
thanks for the contributions! Hopefully I"ll get some time to give it a real look soon, but for now:

> Add testcases that test if faces, edges, etc.. are returned as masked arrays, with masks for unfilled nodes (e.g last node in the triangle in example above). (1 test case added so far)

I think we are better off using a sentinel value than masked arrays -- i.e. -1 for unfilled nodes. masked arrays have performance issues and are not supported by every array-like object we may want to use, nor can they be efficiently passed to C or Fortran code.

> Some .nc files are created in test/files. What is the expected organization of test files and scripts that create them?

This is  a bit chaotic at the moment -- just do something reasonable :-)

I'm a bit on the fence about whether unit test fixtures should clean up stuff like that after running. 

On the one hand, it's clean and tidy, and you  dont end up with a pile of untracked file sin your working tree.

On the other hand, when tests fail, I often want to see the generated files to debug -- and often want to see them when first writing the code and tests -- or even for sanity checking stuff that isn't explicitly tested...

NOTE: @ocefpaf  put some nice fixtures for this in pysgrid:

https://github.com/sgrid/pysgrid/blob/master/pysgrid/tests/write_nc_test_files.py

maybe do something like that?

Also: there are probably a lot of assumptions abuot triangles in the code all over the place, so one of these days we want to make sure to have all the tests run with a non-triangular example.

**Comment by bekozi** [comment]
> @bekozi, please have a look and see how this fits in with the pull request you were working on in #96

@SiggyF I will close that issue - no `pyugrid` development in the near future, so no worries about conflicts!

**Comment by ocefpaf** [comment]
@SiggyF I strongly recommend the use of `pytest` and fixtures for creating and testing with `netCDF` files (or any or file in fact). It keeps the repository "clean" of binaries, the tests are "safer" in the regard that files are created, opened, and closed properly.

I started implementing this kind of testing here in `pyugrid` some time ago, but it is better implemented in `pysgrid`:

https://github.com/sgrid/pysgrid/tree/master/pysgrid/tests

> Best to create the PR on develop. Master is very old at this point

@jay-hennen I understand that some people coming from non-distributed version control system like to have a `develop` branch, but that makes collaboration hard. Not to mention that no work branch should make `master` "old" at any point.

Please, to foster collaboration and good community practices treat `master` as the development version, commit often, use branches for specific purposes PRs (like this one!) and merge often.

Otherwise people will not collaborate. Open Source is not only about code and licenses. It is about good community practices! Having an outdated `master` and dumping a lot of code is virtually the same as closed source development.

**Comment by SiggyF** [comment]
Thanks for all the suggestions. I did the following:
- add some documentation
- update the notebook with a now working example 
- add some more tests 
- follow the sgrid approach for test data with yielding fixtures (which I put in test/files and remain there after an exception I believe, not tested)

On travis the develop branch succeeds in 34 out of 68 tests. After my code update this changes to 37 out of 71. 

As suggested I looked at the parts of the code that are triangle specific. Most of this is in the `build_` routines. I can imagine that we merge this pull request first and that I create a separate pull request on upgrading the `build_` functions to match the now (somewhat) supported flexible meshes and quad grids. 

Please note that this pull request is relative to the develop branch. 

@jay-hennen The flexible mesh as I refer to it here is a mesh of varying number nodes per cell, as in the ugrid convention. I think most people refer to meshes that vary in time as adaptive rather than flexible.

**Comment by SiggyF** [comment]
I have fixed the tests in the develop branch in #143. I would suggest to merge that first so we can properly check if this PR does not break anything.

**Comment by SiggyF** [comment]
With  #143 fixing the tests and the last commits fixing some minor issues in this branch, I would consider this safe to merge. 

As discussed above there are some assumptions on triangulations that could benefit from some further testing. I suggest to merge these changes first and continue the work in a new branch specifically addressing the generalization from triangles to n-sided shapes.

**Pull request merged**
