### PR TITLE
pytest

### PR DESCRIPTION
**Pull request by ocefpaf**
Installing `pytest` from the default channel.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I did not include in the `requirements.txt` to avoid mixing test dependencies with run/install  dependencies.

**Comment by ChrisBarker-NOAA** [comment]
makes sense.

**Comment by ChrisBarker-NOAA** [comment]
I think something is up with travis -- conda install pytest works fine for me -- I actually just got an update...

**Comment by ocefpaf** [comment]
Yep.  I will take a look at this tomorrow.

**Comment by ChrisBarker-NOAA** [comment]
It's failing with:

/home/travis/build.sh: line 175: conda: command not found

so something is up - I'm out of my depth -- tomorrow :-)

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA Travis-CI is green again.  Not sure what happened yesterday.  I guess it was a temporary issue.

**Comment by rsignell-usgs** [comment]
This seems good to go.

**Pull request merged**
