### PR TITLE
Merge Develop into Master?

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
I honestly have no idea if it's ready -- but thought I'd start the conversation.

I suggest will do a  "release" of master, then push develop in an increment the version number.

then folks can easily go back to the master version if they need to, but we can move forward with working of maste, like we probably should have been sooner.

Any objections?

### CODE REVIEW

**Comment by jay-hennen** [comment]
I'm fine with it.

**Comment by ChrisBarker-NOAA** [comment]
Looking at master, it's at v. 0.2.2, which is also the last release -- though it looks like the last release was tagged from develop.... and develop has 0.2.2 hard coded into it, also.

So we need to clean this up one way or another -- I'm thinking increment the version number in develop right before merging it in.

**Comment by SiggyF** [comment]
Was this included in the 0.2.3 release from last April?

**Comment by ChrisBarker-NOAA** [comment]
I don't remember, but looking now, it looks like it wasn't :-( But at a
glance it doesn't look like ugly conflicts, either -- a lot of improved
docstrings, style, etc.

@jay-hennen: what do you think?

-CHB

**Comment by jay-hennen** [comment]
Oof. This fell through the cracks, and there's some good stuff in it too. Some of it's outdated but there's lots of small good things.

Hmm....I think this should be merged, and make a new release. What's unfortunate is that the version of pyugrid that got integrated into `gridded` doesn't have any of these changes. Probably have to do a manual merge to fix that.

**Comment by SiggyF** [comment]
Can I provide any assistance with drafting a new release? I'm working on a project where I use pyugrid for the next few weeks, so I'd be happy to help out.

**Comment by rsignell-usgs** [comment]
@SiggyF , that would be fantastic.   What we really need it just another pair of eyes on this and present back to the group anything you think is wrong or controversial (or missing!).

**Comment by ChrisBarker-NOAA** [comment]
@SiggyF: thanks for the offer!

What I would do first is merge master back into develop (rebase), teste again, and see where we are at.

-CHB

**Comment by SiggyF** [comment]
I merged the latest master into develop, fixed some minor issues (flake8, tests) and created a separate pull request #155 .

**Comment by rsignell-usgs** [comment]
@ChrisBarker-NOAA  and @jay-hennen , you guys are going to review this, right?

**Comment by ChrisBarker-NOAA** [comment]
yup -- maybe our last act on the current pyugrid project.

Then we'll try to get the improvements into gridded -- I think we made the mistake of forking gridded from master, rather than develop...

**Comment by ChrisBarker-NOAA** [comment]
This has been superseded by #155, yes?

**Comment by SiggyF** [comment]
This also contains flexible mesh support. The idea was to first merge the latest developments of master into develop (that's #155) and then this into master. 
That would be a good time to do a new release and perhaps recopy into the gridded software. For me that would be convenient otherwise I would have to do the same pull requests for gridded.

**Comment by ChrisBarker-NOAA** [comment]
OK,

It may have been easier to merge master into develop in your fork, and then have one PR for the whole thing. But I’ll try to go through this tomorrow.

**Comment by SiggyF** [comment]
If I merge master into this branch nothing happens. So I think it is already up to date with master.

**Comment by ChrisBarker-NOAA** [comment]
great --that will make it easier.

I'll TRY to get to this soon!

@jay-hennen , maybe you could take a look.

**Comment by SiggyF** [comment]
Please let me know if I can do anything else to facilitate this merge.

**Comment by ChrisBarker-NOAA** [comment]
I don’t think so — I just need to find the time to review it.

You did confirm all the tests pass, yes?

-CHB

Sent from my iPhone

On Dec 5, 2017, at 1:38 AM, Fedor Baart <notifications@github.com> wrote:

Please let me know if I can do anything else to facilitate this merge.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pyugrid/pyugrid/pull/144#issuecomment-349248814>, or mute
the thread

**Comment by SiggyF** [comment]
Yep `71 passed in 0.93 seconds`.

**Comment by SiggyF** [comment]
One thing I did not do, is bump the version number. That would be good to do before releasing the master.

**Comment by ChrisBarker-NOAA** [comment]
Thanks — and why don’t you bump the version number in The PR -/ then it’ll be ready to go.

**Comment by SiggyF** [comment]
People sometimes bump the version as part of the release. I raised it to 0.3.0.

**Comment by SiggyF** [comment]
Just to be clear I have merged the current version of pyugrid/master into my develop branch. 
That is PR #155 . This is the merge of the current develop into master. The current develop branch has some linting errors and minor bugs. These are all fixed in PR #155.  So I would suggest to first merge #155 and then this one #144. Then we should have a new release ready.

**Comment by ChrisBarker-NOAA** [comment]
Thanks!

Anyone test is the cell_tree point-in-cell works with the flexible-mesh? 

I'm guessing now, I think it'd get confused.

But this is adding functionality, not taking it away, so Im merging.

**Comment by SiggyF** [comment]
Thanks!

**Pull request merged**
