### PR TITLE
Fix tiny bug

### PR DESCRIPTION
**Pull request by ocefpaf**
Fix a minor bug  of a string format statement that used mixed syntax.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Travis is broken... Got to love when a tiny PR needs to fix another issue.

That is probably some incompatibility with the latest numpy version.  I am working on it.

**Comment by ChrisBarker-NOAA** [comment]
yup -- got to love it!

will this tiny fix be in the other pull request?

**Comment by ocefpaf** [comment]
Nope. I am waiting for #102 to rebase and finish #101.

**Comment by ChrisBarker-NOAA** [comment]
as long as it gets in there... :-)

On Tue, Oct 20, 2015 at 8:58 AM, Filipe <notifications@github.com> wrote:

> Nope. I am waiting for #102 <https://github.com/pyugrid/pyugrid/pull/102>
> to rebase and finish #101 <https://github.com/pyugrid/pyugrid/pull/101>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyugrid/pyugrid/pull/101#issuecomment-149615113>.
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I am confused **does**  #102 fixes the bug I found while implementing the this PR here.  Do you want me to port the fix here to the other PR?  They are unrelated, but I can do that...

**Comment by ChrisBarker-NOAA** [comment]
On Tue, Oct 20, 2015 at 9:15 AM, Filipe <notifications@github.com> wrote:

> @ChrisBarker-NOAA <https://github.com/ChrisBarker-NOAA> I am confused
> *does* #102 <https://github.com/pyugrid/pyugrid/pull/102> fixes the bug I
> found while implementing the this PR here. Do you want me to port the fix
> here to the other PR? They are unrelated, but I can do that...
>

however you wan to do it is fine. I was just thinking that since you found
the other bug while trying to push this one, it might be on the same
branch. This is tiny enough that it doesn't need it's own PR -- but if it's
easier, go for it :-)




> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyugrid/pyugrid/pull/101#issuecomment-149619929>.
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by ocefpaf** [comment]
> but if it's easier, go for it :-)

It is already done.  So that is easier for me!

BTW I like to keep fixes in their own context.  Easier to review and keep track of the changes.

**Comment by rsignell-usgs** [comment]
merging this so we can move on

**Pull request merged**
