### PR TITLE
Celltree&interpolation

### PR DESCRIPTION
**Pull request by jay-hennen**
This branch contains addition of the CellTree. Also included is a locate_faces function and bilinear interpolation function that both make use of it.

See https://github.com/NOAA-ORR-ERD/cell_tree2d for more information on what a CellTree is and what it does. In short, it is a balanced BVH that efficiently locates which indexed face contains a point in question.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
These failures seem to have nothing to do with the code -- rather a problem getting conda up and running. Maybe they will fix themselves

**Comment by ocefpaf** [comment]
> These failures seem to have nothing to do with the code -- rather a problem getting conda up and running. Maybe they will fix themselves

Chris, we need to fix this because conda is trying to install a package that does not exist there yet: `cell_tree2d`.  We must get `cell_tree2d` from a custom channel.

**Comment by ChrisBarker-NOAA** [comment]
Indeed -- I should have noticed that. dependency heck!

celltree2-d should be compilable without anything special -- so I suppose we should ut it up on PyPi at some point.

**Comment by ChrisBarker-NOAA** [comment]
OK -- need to make celltree-2d more available before we can do anything with this. Jsut putting this comment in to ping myself :-)

@jay-hennen: we should make sure to have conda packages available, and maybe put it up on PyPi -- that should be straightforward.

@ocefpaf: is there a conda channel we can put it up on? or can we point to our channel somehow?

https://anaconda.org/noaa-orr-erd/cell_tree2d

**Comment by ocefpaf** [comment]
> OK -- need to make celltree-2d more available before we can do anything with this. 

:+1: 

> @ocefpaf: is there a conda channel we can put it up on? or can we point to our channel somehow?

I was just waiting for an official release to update and merge https://github.com/ioos/conda-recipes/pull/632.

I can also send `celltree-2d` to `conda-forge` as soon as we have a working and tested version on our channels.

Note that when I send a package to `conda-forge` I drop support for the recipe on the IOOS, but I still fetch the recipe from `conda-forge` and re-build it on IOOS.  That way we maintain 1 recipe and keep both channels up-to-date.  This workflow will be sustained until we move to `conda-forge` entirely.

**Comment by ChrisBarker-NOAA** [comment]
OK -- we'll make an "official" release of celltree2d -- they'll be a prerequisite to merging this code in.

**Comment by rhattersley** [comment]
> rhattersley deleted the celltree&interpolation branch just now

It'd be good to develop in your own fork, rather than this repo.

**Comment by ChrisBarker-NOAA** [comment]
OK -- I have a process question here. 

First -- if you have a large project with a few folks with commit rights, and a larger community making small contributions, then they need to use a fork to do that, yes.

But I actually find it harder to deal with a PR from a separate fork. I can't then go in and look at and even edit that fork. I'd have to then fork the fork, make a change, do a PR to the fork, then that user can merge that PR, and then that will be reflected in the original PR -- but this is a lot of process.

Whereas if someone makes a change in a branch, and does a PR on that, it's a lot easier for the core contributors to work on that same branch to clean up the PR. As long as we follow the same:

change, PR, review, merge

Process then I fail to see the point in using a fork -- it's just extra overhead.

-CHB

**Comment by nikhil003** [comment]
Hi,

sorry to dig up old post

this is more of a suggestion, enhancement to pyugrid. I am not sure how keen pyugrid developers are towards adding more libraries to it, in my work i rely on "nn" and "csa" libraries developed by Pavel Sakov for grid interpolation.

https://github.com/sakov

these are written in C and i created a Cython based wrapper around them, which is using a class object thereby making some parts of the code persistent. I would be happy to contribute that to pyugrid community.

"nn" is used for nearest neighbour and "csa" is for cubic spline approximation. Also, just to add, both of these libraries, i used quite regularly on windows, where i just used compiler supplied by Micrsoft for compiling.

Btw, the "nn" library also comes with its own KDTree and delaunay, which might remove the need to have scipy, though by adding extra dependencies.

**Comment by jay-hennen** [comment]
I personally am fine with adding more functions like this but adding the new library is the larger concern for the project overall. 

What additions specifically are you proposing? (new/altered Python functions, specific dependencies, new/altered abilities, etc)

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- cool stuff -- kinda wish I'd seen it before...

My thought would be to make a pacakge of this stuff -- the cython wrappers and C code.

Then have pyugrid and maybe pysgrid have an optional dependency on that package.

**Pull request merged**
