### PR TITLE
Interoperable velocity example

### LINKED ISSUE #60: Add an example notebook that plots velocity vectors using pyugrid
Does anyone have an example notebook that shows how to use pyugrid to plot velocity vectors from any UGRID-compliant model (e.g. without model specific code)?

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs I realized that we don't need `pyugrid` at all interoperable velocity plotting.

http://nbviewer.jupyter.org/github/ocefpaf/pyugrid/blob/d77cc9718e089d2e97f0eb0e266723e689ab3af2/notebook_examples/vector_plotting_example.ipynb

Since CF takes care of it iris is enough for this example.

Closes #60

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf ,ah, sneaky.  So this is just using the regular "coordinates" attribute associated with the variable.    
 
We should make this UGRID interoperable example have arrows on top of triangles colored by speed.  *Then* we would be forced to use the coordinates information contained in the mesh variable!

**Comment by ocefpaf** [comment]
> We should make this UGRID interoperable example have arrows on top of triangles colored by speed. *Then* we would be forced to use the coordinates information contained in the mesh variable!

Do we have an issue from `ugrid` plotting?  I guess that information should be there.

**Comment by ChrisBarker-NOAA** [comment]
It's be nice to be able to do all of this without IRIS -- it's a bit weird to mix them in my mind (but maybe that's just my mind). But anyway, it would be nice to have a bunch of plotting routines available out of the box with py_ugrid (and s_grid...)

**Comment by ocefpaf** [comment]
>  it's a bit weird to mix them in my mind (but maybe that's just my mind).

I understand that.  It was weird for me too, but since I start seeing `pysgrid`, `pyugrid`, and `iris` as interpretations of `SGRID`, `UGRID`, and `CF-conventions` respectively I kind of made my peace with it.

(Basically change your mind from scientist to a bureaucrat and it will work :wink:)

**Pull request merged**
