### PR TITLE
Extract version from __init__.py

### PR DESCRIPTION
**Pull request by ocefpaf**
That way we maintain the version number in only one file and we do not need to import `pyugrid` to get the version.

Note that I also pep8'd `setup.py `.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@cbcunc I modified it to read from the `VERSION.txt` and added a crappy way to update the `__init__.py`, not sure if that is the way to go...

**Comment by ChrisBarker-NOAA** [comment]
The __init__version string should get replaces with a new one, which will now be there. So teh setup.py shoulud replace __version__ = "any old thing" with the new version:

Something like (untested):

def inplace_change(filename, new_version=__version__):
    with open(filename) as f:
        lines = f.readlines()
        for i, enumerate( lines ):
            if line.strip().replace(' ','').startswith("__version__="):
                lines[i] = "__version = %s\n"%new_version
                break

       f = open(filename, 'w').writelines(lines)

**Comment by ocefpaf** [comment]
Got it.  Fixing it...

**Comment by daf** [comment]
I'm rather confused by this "automatic patching of `__init__.py` every time i do anything with setup" behavior, it's not a pattern I've ever seen before.  Why `VERSION.txt` on its own and not in `__init__.py`?  Wouldn't this give issues to someone who installed to system python (admittedly rare to operate with the setup.py in there)?

**Comment by ChrisBarker-NOAA** [comment]
I'm rather confused by this "automatic patching of __init__.py every time i
do anything with setup" behavior, it's not a pattern I've ever seen before.

Well, we all agree it's a hack ;-)

Why VERSION.txt on its own and not in __init__.py?

This is a pattern seeing wider use -- we want tools to be able to parse out
the version without importing anything, or parading out python. Or knowing
that the package __init__.py is where to look for version info.

And tools asside, for users to have an obvious place to look.

Meanwhile, it needs to be in the package run time, and available with
"setup.py --version"

And, of course, there needs to be one place to specify the version.

So this is the hack we came up with to accommodate all that.

Less kludgy suggestions greatly appreciated!

Note that git uses hashes, rather than modification times to determine a
change, so this shouldn't trigger constant meaningless changes to
__init__.py in the git history.

Wouldn't this give issues to someone who installed to system python
(admittedly rare to operate with the setup.py in there)?


How so? You never run setup.py on installed files. It's not even installed
at all, is it?

And when setup.py is run, the user needs permissions to write to the source
dir anyway. Though not necessarily to the source itself....would that come
up?

-CHB

**Comment by pelson** [comment]
> That way we maintain the version number in only one file

Even that is one file too many. Git has all the information you need, and if it is a source tar ball created from git, git can inject the necessary magic for you. Versioneer is your friend :)

**Comment by ChrisBarker-NOAA** [comment]
FAir enough -- I created an issue for that, to keep it on our radar:

#90

**Pull request merged**
